### ISSUE TITLE
Feature Request: Ability to use command inside a chat message

### ISSUE THREAD

**Issue by Kurohyou** [DJDavid98/HammerTimeBot#13]
It'd be useful to be able to include the autogenerated timestamps inline with a discord chat message. This would require a way to limit the output to only a specific time output (e.g. `8/8/2022` or `4:00 PM`).

I'd imagine the syntax being something like:

```
Here's my discord message where I say I'd like to schedule our meeting for !timestamp-1600.
```

Would then output  something like:
```
Here's my discord message where I say I'd like to schedule our meeting for [1600].
```
Where [1600] would be localized to everyone's individual timezone.

**Comment by DJDavid98** [comment]
This requires the recently introduced privileged intents from Discord that enables reading all message contents, which requires separate justification (e.g. moderation purposes) to have access to. Discord ToS specifically disallows using this intent for the purposes of executing automated commands, and I do not intend to apply for more permissions than necessary.

No plans to implement this now or in the future, but I sincerely hope that Discord makes this a native feature at some point.
