### ISSUE TITLE
Properly support user installs

### ISSUE THREAD

**Issue by DJDavid98** [DJDavid98/HammerTimeBot#60]
Allow all commands to be ran from user context

**Comment by MinerPL** [comment]
Support can be added in two ways
* In each command (picture one).
* In the function from downloading all commands (picture two).


Which one will be better?
![idea64_DVQ17gfPKx](https://github.com/DJDavid98/HammerTimeBot/assets/37021230/f3c5c743-4a0c-4188-ae2b-3a39abb451f5)
![idea64_IRqAoHPs6s](https://github.com/DJDavid98/HammerTimeBot/assets/37021230/8e872610-fda1-42a9-8a5e-0b3e6200be76)

**Comment by EntityPlantt** [comment]
> Support can be added in two ways
> * In each command (picture one).
> * In the function from downloading all commands (picture two).
>
> Which one will be better?

Do you have any commands that are only for servers? If yes, the first one is the choice. If no (correct answer) the second one is much cleaner (you can add more common options with 1 line)

**Comment by MinerPL** [comment]
> Do you have any commands that are only for servers? 
From what DJDavid98 writes it is about all commands, the bot itself does not have any commands that must be used on the server
