### ISSUE TITLE
Incorrect ephemeral helptext

### ISSUE THREAD

**Issue by budak7273** [DJDavid98/HammerTimeBot#66]
The current message for the `ephemeral` parameter to the `at` command states that the parameter defaults to false, but this no longer seems to be the case.

https://github.com/DJDavid98/HammerTimeBot/blob/main/src/locales/en-US/translation.json#L209

For example, running the command `/at hour:7 minute:0 timezone:CST6CDT` with the bot produces an ephemeral message.

![image](https://github.com/user-attachments/assets/6b9ad1c0-71b5-4d58-ad1b-3caaff2cc769)

![image](https://github.com/user-attachments/assets/9cc92009-6aa6-46f5-96da-a6930b0dc879)

Specifically supplying `False` or `True` to the argument results in the correct behavior.

I personally prefer ephemeral to be on by default (the current behavior), but the helptext does not currently match this.

**Comment by DJDavid98** [comment]
Fair point. Since user settings have been introduced, the default part no longer makes sense either way, so I will be getting rid of that.

**Comment by DJDavid98** [comment]
Bot update has been deployed and shards are currently restarting, it may take up to an hour (according to Discord's API docs) to update the global command text across the app. Thank you for the feedback, I genuinely did not catch this myself.

**Comment by budak7273** [comment]
@DJDavid98 It seems like the default information is now entirely absent. Was that intended? 
![image](https://github.com/user-attachments/assets/afde2693-58d6-4b47-9b0f-74519de7466f)

**Comment by DJDavid98** [comment]
Yes, I explained it in my previous comment I believe
